---
- name: Configure OPS445 Lab VM
  hosts: vmlab
  user: student
  become: yes

  tasks:
    - name: update Apache httpd to latest
      yum:
        name: httpd
        state: latest

    - name: ensure EPEL repository is installed
      yum:
        name: epel-release
        state: present

    - name: remove tree package if installed
      yum:
        name: tree
        state: absent

    - name: set system hostname
      hostname:
        name: jwang557

    - name: create a new user with sudo (wheel) access
      user:
        name: jwang557
        groups: wheel
        state: present
        create_home: yes
        shell: /bin/bash

    - name: copy SSH public key for new user
      authorized_key:
        user: jwang557
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: create ops445 directory for new user
      file:
        path: "/home/jwang557/ops445"
        state: directory
        owner: jwang557
        group: jwang557
        mode: '0755'

    - name: create lab1 to lab8 directories for new user
      file:
        path: "/home/jwang557/ops445/{{ item }}"
        state: directory
        owner: jwang557
        group: jwang557
        mode: '0755'
      loop:
        - lab1
        - lab2
        - lab3
        - lab4
        - lab5
        - lab6
        - lab7
        - lab8
